const dicas = [
  "Sempre adicione mais ponto e vírgula, nunca se sabe quando vai precisar.",
  "Se não funcionar, copia e cola o erro no Google e reza.",
  "Console.log é seu melhor amigo (até mais que gente).",
  "Se não entendeu o código, bota um comentário: // magia negra",
  "Nunca confie no código que funciona de primeira. Algo está errado!",
  "Quanto mais !important no CSS, mais importante você se torna.",
  "Se o bug sumiu depois de um npm install, é porque ele te respeita.",
  "Não sabe o que faz? Renomeia pra final.js e segue em frente.",
  "Se o código tá funcionando, não mexe. Nem pra comentar.",
  "Erro 404? Atualiza a página. Não resolveu? Chora.",
  "Variável com nome misterioso? Melhor deixar assim mesmo – já tá acostumado.",
  "Se não sabe o que faz, coloca // TODO: entender isso aqui e segue a vida.",
  "Commit de madrugada é igual mensagem de bêbado: depois você nem entende.",
  "Se o cliente pede algo impossível, diz 'é só uma configuração' e some por uma semana.",
  "Testar em produção? Claro! (Mas só se não tiver usuário de verdade).",
  "Se o código tá lento, compra um PC melhor. Problema resolvido.",
  "Marca reunião para explicar o código que você não entende. Alguém vai entender por você.",
  "Se der erro, troca a linguagem. JavaScript virou TypeScript? Quase a mesma coisa.",
  "Quer ser produtivo? Desinstala o Twitter. Mas instala o TikTok (para 'inspiração').",
  "Se o chefe pergunta quanto tempo falta, responde 'uns 2 dias' – mesmo que faltem 2 meses.",
  "Código legível? Isso é mito. Só você mexe mesmo.",
  "Se não consegue resolver, coloca um setTimeout e torce.",
  "Se tudo der errado, formata o PC. Começar do zero é terapêutico.",
  "Se o código tá lento, adiciona um setTimeout. Parece que resolve.",
  "Variável sem uso? Chama de foo e ninguém vai questionar.",
  "Se o deploy deu certo, é porque você esqueceu de testar alguma coisa.",
  "Não precisa entender o regex. Só copia do Stack Overflow e finge que sabe.",
  "Quanto mais try/catch, menos dor de cabeça. Ou mais, depende.",
  "Se o layout quebrou, culpa do navegador. Sempre.",
  "Documentação é só spoiler. Descubra o código por conta própria.",
  "Se o código tá feio, joga num dark theme e finge que é estiloso.",
  "Não precisa apagar código antigo. Comenta tudo e chama de legado.",
  "Se o bug só aparece às vezes, então ele não existe de verdade.",
  "Quanto mais frameworks, mais profissional você parece. Mesmo sem saber usar.",
  "Se o cliente não reclamou, então tá funcionando. Provavelmente.",
  "Testar em produção é o teste mais realista que existe.",
  "Sempre programe tarde da noite. Os bugs ficam com sono e não aparecem.",
  "Se o código estiver lento, culpe o usuário ou a conexão, nunca o seu algoritmo O(n^n).",
  "Qualquer problema pode ser resolvido com um 'setTimeout' gigante.",
  "Apague todas as mensagens de erro. Se você não as vir, elas não existem.",
  "Comentários são para os fracos. Código bom se explica sozinho (e ninguém nunca entende).",
  "Sempre adicione um 'alert()' no meio do código. É o melhor debugger visual.",
  "Se a função tiver mais de 500 linhas, ela é uma função robusta e completa.",
  "Troque o nome das variáveis para letras aleatórias. Ajuda a prevenir que outros mexam no seu código.",
  "Nunca documente nada. A documentação fica desatualizada rápido demais.",
  "Se o seu código travar, é um feature, não um bug. O programa está apenas pensando.",
  "Sempre use ID em todos os elementos HTML. CSS é para quem tem tempo.",
  "Para otimizar o código, remova todos os espaços. Diminui o tamanho do arquivo.",
  "Se o cliente pedir uma funcionalidade impossível, diga que está 'em fase de otimização complexa'.",
  "Esqueceu uma chave? Adicione no final do arquivo. O compilador encontra o lugar certo.",
  "Commit sempre com mensagem 'fix' - ninguém precisa saber o que realmente foi feito.",
  "Se o código está muito complexo, ameaça deletar tudo. Às vezes ele se conserta sozinho.",
  "Ctrl+C + Ctrl+V > Saber programar (às vezes).",
  "Se tá funcionando, NÃO MEXE. Nem pra 'melhorar'.",
  "Comentário mais útil: // não mexe aqui que quebra tudo",
  "Teste? Ah, o usuário que teste pra gente.",
  "Se não sabe como funciona, chama de 'feature' e não de 'bug'.",
  "Stack Overflow é meu pai, meu pai e meu avô espiritual.",
  "Deadline chegando? É hora de aprender uma tecnologia nova em 2 horas!",
  "Se o código está feio mas funciona, está perfeito. Bonito é pra foto.",
  "Não sabe o que faz? Cria uma função chamada doStuff() e finge que tá tudo sob controle.",
  "Se o botão não funciona, aumenta o tamanho da fonte. Vai que é falta de atenção.",
  "Nunca apague um console.log. Ele pode estar segurando o sistema.",
  "Se o bug sumiu depois de você olhar feio pro monitor, é porque ele te respeita.",
  "Mais divs, menos problemas. Layout quebrado? Envolve tudo em mais uma div.",
  "Se o código tá lento, adiciona um spinner. Pelo menos parece que tá fazendo algo.",
  "Não precisa entender o this. Só evita usar e segue a vida.",
  "Se o erro é de sintaxe, culpa do teclado. Sempre.",
  "Quanto mais else if, mais inteligente parece. Mesmo que ninguém entenda.",
  "Se o deploy falhou, culpa do Mercúrio retrógrado.",
  "Não sabe que nome dar pra variável? banana nunca decepciona.",
  "Se o código tá funcionando, não mexe. Nem olha. Nem respira perto.",
  "Se tudo der errado, muda a cor do botão. Pelo menos parece que você fez algo.",
  "Sexta-feira à tarde: melhor horário pra deploy em produção.",
  "Se der erro, culpa o framework. Nunca você.",
  "Documentação? Ah, o código É a documentação (mentira).",
  "Se não consegue resolver, dorme. O cérebro debuga sozinho durante o sono.",
  "Sempre tenha um plano B para quando o plano A não funcionar... e um plano C para quando o B também falhar.",
  "Use cores aleatórias no CSS até que alguém reclame - é uma forma de arte moderna.",
  "Quando em dúvida, refatore o código inteiro e veja se o problema some por mágica.",
  "Nunca subestime o poder de um café forte para resolver um bug teimoso.",
  "Se o código está muito limpo, provavelmente está faltando um bug escondido em algum lugar.",
  "Comenta tudo, até o que você acha que é óbvio - seu eu de amanhã vai agradecer (ou não).",
  "Para cada problema, há uma solução... ou um workaround ainda mais complicado.",
  "Não se preocupe com performance até que o site comece a carregar em tempo real de uma supernova.",
  "Use variáveis com nomes como 'coisa', 'treco' e 'bagulho' - é uma forma de abstração criativa.",
  "Se o deploy falhar, tente novamente com mais café e menos sono.",
  "Todo código tem um propósito... ou um propósito oculto que só o bug sabe.",
  "Não confunda 'funciona no meu computador' com 'funciona em produção' - são coisas bem diferentes.",
  "Para bugs difíceis, tente desligar o computador e ligar de novo - tecnologia espacial.",
  "Sempre deixe um pouco de código 'morto' pelo projeto - é um bom fertilizante para o próximo bug.",
  "Quando o código não compila, tente sacrificar um pixel ao deus da programação.",
  "Se o bug não some, provavelmente é porque você esqueceu de rezar para o santo do JavaScript.",
  "Nunca tente consertar um bug às 3h da manhã - é quando os bugs se multiplicam como coelhos.",
  "A solução para todo problema de código é mais café... ou menos sono, depende do ponto de vista.",
  "Se você não entende o que o código faz, provavelmente é porque ele foi escrito por um gênio ou um inimigo.",
  "Todo projeto tem um 'ponto de não retorno' - é quando você percebe que deveria ter usado outra linguagem.",
  "Para bugs persistentes, tente a 'terapia do reboot' - desligue tudo e veja se o universo se consertou.",
  "Não se preocupe com a legibilidade do código - quem vai manter é um robô com um senso de humor questionável.",
  "Quando em dúvida, adicione mais bibliotecas - é como adicionar mais tempero a uma receita ruim.",
  "Se tudo mais falhar, culpe o hardware - é uma forma de externalizar o problema (e a culpa).",
  "Renan, me aprova pelamor de Deus, eu tenho TDAH não diagnosticado",
  "Quando tudo mais falhar, leia a documentação... ou peça ajuda a um colega que jura que sabe o que está fazendo.",
];

document.getElementById("btnDica").addEventListener("click", () => {
  const aleatorio = Math.floor(Math.random() * dicas.length);
  document.getElementById("dica").innerText = dicas[aleatorio];
});
